config/routes.rb
Rails.application.routes.draw do
  root to: 'github_repositories#index'
  get '/index', to: 'github_repositories#index', as: 'index'
  get '/github_repositories_search', to: 'github_repositories#search', as: 'github_repositories_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_repositories_controller.rb
# frozen_string_literal: true

# search and display github repositories
class GithubRepositoriesController < ApplicationController
  def index
    @repos = []
  end

  def search
    @repos = fetched_repos
    flash[:error] = nil if @repos.present?
    render :index
  end

  private

  def github_searcher
    @github_searcher ||= GithubSearch::Searcher.new
  end

  def fetched_repos
    search_param.present? ? github_searcher.repos.search(search_param, sort: :stars) : []
  end

  def search_param
    @search_param ||= params.require(:search)
  rescue ActionController::ParameterMissing
    flash[:error] = 'Please enter a repository name.'
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_repository_helper.rb
module GithubRepositoryHelper
end

app/views/github_repositories/index.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<h1>Github Repository Searcher!</h1>

<%= form_with(url: github_repositories_search_path, method: :get) do |form| %>
  <%= form.label(:search, 'Please enter a repository name:') %>
  <%= form.text_field(:search, value: params[:search]) %>
  <%= form.submit("Search") %>
<% end %>

<br />
<ul>
  <% @repos.each do |repo| %>
    <li><%= link_to repo.full_name, repo.html_url, target: "_blank" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RepositorySearcher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>